application: trippal-1520
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static.*
  static_dir: static
  
- url: /stylesheets
  static_dir: stylesheets

- url: /weeklyMail
  script: main.app
  login: admin
  
- url: /.*
  script: main.app
